[package]
name = "rgit"
version = "0.1.0"
authors = ["Yuiki <10101661+Yuiki@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9.1"
hex = "0.4.2"
flate2 = "1.0.16"
